server:
  port: 8080

spring:
  profiles:
    active: dev
  logging:
    level:
      org.springframework: INFO
      com.pablo.digitalstore: DEBUG

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "http://localhost:8080/api/v1/oauth2/callback"
            scope:
              - email
              - profile

  app:
    jwt:
      secret: ${JWT_SECRET}
      expiration-ms: ${JWT_EXPIRATION_MS}

  devtools:
    restart:
      enabled: true