spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/digital-goods-db
    username: postgres
    password: pablo1996
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
